adjustment deployment script

diff --git a/.github/workflows/deployment.yml b/.github/workflows/deployment.yml
--- a/.github/workflows/deployment.yml
+++ b/.github/workflows/deployment.yml
@@ -40,6 +40,15 @@ jobs:
 
       - name: Lint
         run: pnpm lint
+        
+      - name: Check if Secret is present (Local Runner)
+        run: |
+          if [ -z "${{ secrets.SSH_PRIVATE_KEY }}" ]; then
+            echo "ERROR: SSH_PRIVATE_KEY is not defined in GitHub Secrets!"
+            exit 1
+          else
+            echo "OK: SSH_PRIVATE_KEY is detected."
+          fi
 
       - name: Deploy to server
         uses: appleboy/ssh-action@v1.2.0
@@ -47,6 +56,7 @@ jobs:
           host: 103.217.144.200
           username: farros
           key: ${{ secrets.SSH_PRIVATE_KEY }}
+          # Script di bawah ini hanya jalan KALAU koneksi SSH sudah sukses
           script: |
             cd live
             git pull
